# Multi variable linear regression(1)

In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
# dataset
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [4]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [5]:
hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [6]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [9]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 ==0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  62547.29 
Prediction:
 [-75.96345  -78.27629  -83.83015  -90.80436  -56.976482]
10 Cost:  14.468628 
Prediction:
 [145.26407 187.59541 178.152   194.48586 145.81136]
20 Cost:  13.822504 
Prediction:
 [145.9478  188.39003 178.94907 195.3521  146.41212]
30 Cost:  13.749193 
Prediction:
 [145.96422 188.38263 178.95592 195.35777 146.4012 ]
40 Cost:  13.67629 
Prediction:
 [145.97856 188.3728  178.96031 195.36082 146.38844]
50 Cost:  13.603813 
Prediction:
 [145.99286 188.36302 178.9647  195.36386 146.37572]
60 Cost:  13.531695 
Prediction:
 [146.00711 188.35324 178.9691  195.3669  146.36302]
70 Cost:  13.459941 
Prediction:
 [146.02135 188.34352 178.9735  195.36995 146.35036]
80 Cost:  13.388664 
Prediction:
 [146.03552 188.33382 178.97784 195.37292 146.33774]
90 Cost:  13.317709 
Prediction:
 [146.04967 188.32413 178.98221 195.37595 146.32515]
100 Cost:  13.247165 
Prediction:
 [146.06377 188.31447 178.98654 195.37894 146.31259]
110 Cost:  13.176931 
Prediction:
 [146.07785 188.3

1000 Cost:  8.234492 
Prediction:
 [147.18959 187.54395 179.33308 195.61716 145.31201]
1010 Cost:  8.191359 
Prediction:
 [147.20064 187.53638 179.33647 195.61946 145.30222]
1020 Cost:  8.148496 
Prediction:
 [147.21164 187.52884 179.33987 195.62177 145.29245]
1030 Cost:  8.105882 
Prediction:
 [147.22263 187.52136 179.34326 195.62408 145.28271]
1040 Cost:  8.063466 
Prediction:
 [147.23357 187.51385 179.34663 195.62639 145.273  ]
1050 Cost:  8.021268 
Prediction:
 [147.24449 187.50638 179.34999 195.6287  145.2633 ]
1060 Cost:  7.9793425 
Prediction:
 [147.25537 187.49893 179.35335 195.63098 145.25365]
1070 Cost:  7.937602 
Prediction:
 [147.26624 187.4915  179.35669 195.63326 145.244  ]
1080 Cost:  7.8960905 
Prediction:
 [147.27707 187.48409 179.36002 195.63553 145.23439]
1090 Cost:  7.854848 
Prediction:
 [147.28787 187.47672 179.36336 195.63782 145.22482]
1100 Cost:  7.8137712 
Prediction:
 [147.29865 187.46933 179.36667 195.64008 145.21526]
1110 Cost:  7.772931 
Prediction:
 [147.