# Multi variable linear regression

In [1]:
import tensorflow as tf
tf.set_random_seed(777)

In [2]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [3]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [4]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [5]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).


In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [7]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [9]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [12]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [13]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    print("x_batch: \n", x_batch, "\ny_batch: \n", y_batch)
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 ==0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
0 Cost:  7070.9795 
Prediction:
 [[235.22784]
 [282.40146]
 [278.39618]
 [303.91577]
 [214.62396]
 [159.15425]
 [228.5351 ]
 [170.92644]
 [264.65048]
 [246.59116]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
80 Cost:  4.5892305 
Prediction:
 [[154.08513]
 [184.90749]
 [182.31587]
 [199.2939 ]
 [140.26295]
 [104.36064]
 [150.23799]
 [112.9032 ]
 [173.56346]
 [162.26251]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
160 Cost:  4.545466 
Prediction:
 [[154.05653]
 [184.91896]
 [182.30199]
 [199.29817]
 [140.2671 ]
 [104.39891]
 [150.2571 ]
 [112.93827]
 [173.60847]
 [162.35112]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
190 Cost:  4.5301604 
Prediction:
 [[154.04611 ]
 [184.92314 ]
 [182.29692 ]
 [199.29973 ]
 [140.2686  ]
 [104.41288 ]
 [150.26411 ]
 [112.951164]
 [173.62492 ]
 [162.38351 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]

220 Cost:  4.515447 
Prediction:
 [[154.03584 ]
 [184.92725 ]
 [182.29192 ]
 [199.30127 ]
 [140.27003 ]
 [104.42664 ]
 [150.27104 ]
 [112.963905]
 [173.64111 ]
 [162.41545 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
350 Cost:  4.45799 
Prediction:
 [[153.99303 ]
 [184.94421 ]
 [182.271   ]
 [199.3078  ]
 [140.27576 ]
 [104.48401 ]
 [150.30026 ]
 [113.017555]
 [173.70862 ]
 [162.54883 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
460 Cost:  4.4165792 
Prediction:
 [[153.95888]
 [184.9576 ]
 [182.25421]
 [199.31303]
 [140.28001]
 [104.52977]
 [150.3239 ]
 [113.06101]
 [173.76245]
 [162.65553]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [

x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
570 Cost:  4.381089 
Prediction:
 [[153.92659]
 [184.97014]
 [182.23827]
 [199.31813]
 [140.2838 ]
 [104.57312]
 [150.3466 ]
 [113.10277]
 [173.81346]
 [162.75694]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
670 Cost:  4.3533144 
Prediction:
 [[153.8987 ]
 [184.98082]
 [182.22444]
 [199.32256]
 [140.28683]
 [104.61054]
 [150.36644]
 [113.13933]
 [173.8575 ]
 [162.84471]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
800 Cost:  4.322957 
Prediction:
 [[153.8645  ]
 [184.99382 ]
 [182.20741 ]
 [199.32811 ]
 [140.29027 ]
 [104.656494]
 [150.3912  ]
 [113.184906]
 [173.9116  ]
 [162.9529  ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]


x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
860 Cost:  4.3108773 
Prediction:
 [[153.84943]
 [184.99945]
 [182.19986]
 [199.33057]
 [140.29164]
 [104.67673]
 [150.40222]
 [113.20523]
 [173.9354 ]
 [163.00064]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
920 Cost:  4.299921 
Prediction:
 [[153.83482 ]
 [185.0049  ]
 [182.19252 ]
 [199.33296 ]
 [140.29291 ]
 [104.696365]
 [150.41302 ]
 [113.22513 ]
 [173.95853 ]
 [163.04707 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]


x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

1150 Cost:  4.2671213 
Prediction:
 [[153.78275 ]
 [185.024   ]
 [182.1662  ]
 [199.34177 ]
 [140.2968  ]
 [104.76645 ]
 [150.4523  ]
 [113.297554]
 [174.04105 ]
 [163.21355 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

1240 Cost:  4.2577085 
Prediction:
 [[153.76396 ]
 [185.03078 ]
 [182.15663 ]
 [199.34502 ]
 [140.29793 ]
 [104.79176 ]
 [150.46681 ]
 [113.324326]
 [174.07085 ]
 [163.27397 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
1270 Cost:  4.2549286 
Prediction:
 [[153.75787]
 [185.03293]
 [182.15352]
 [199.34607]
 [140.29826]
 [104.79996]
 [150.47153]
 [113.33305]
 [174.08049]
 [163.29355]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch:

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
1400 Cost:  4.244876 
Prediction:
 [[153.73259 ]
 [185.04185 ]
 [182.14055 ]
 [199.35054 ]
 [140.29945 ]
 [104.834045]
 [150.49146 ]
 [113.36986 ]
 [174.12064 ]
 [163.37532 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]


x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
1500 Cost:  4.23909 
Prediction:
 [[153.71423]
 [185.04822]
 [182.13107]
 [199.35385]
 [140.30011]
 [104.8588 ]
 [150.50616]
 [113.39703]
 [174.14978]
 [163.43494]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]

x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [

x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]

 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]]
x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [1

x_batch: 
 [[53. 46. 55.]
 [69. 74. 77.]
 [47. 56. 60.]
 [87. 79. 90.]
 [79. 70. 88.]
 [69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]] 
y_batch: 
 [[101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]]
x_batch: 
 [[93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]
 [82. 86. 90.]
 [86. 82. 89.]
 [78. 83. 85.]
 [76. 83. 71.]
 [96. 93. 95.]] 
y_batch: 
 [[192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
1940 Cost:  4.228961 
Prediction:
 [[153.6438 ]
 [185.07172]
 [182.09416]
 [199.36708]
 [140.30067]
 [104.95405]
 [150.56499]
 [113.5059 ]
 [174.26198]
 [163.66647]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.

x_batch: 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]] 
y_batch: 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]]
1970 Cost:  4.2289824 
Prediction:
 [[153.63956 ]
 [185.07306 ]
 [182.0919  ]
 [199.36792 ]
 [140.30058 ]
 [104.95979 ]
 [150.56866 ]
 [113.512726]
 [174.26877 ]
 [163.68059 ]]
x_batch: 
 [[69. 70. 73.]
 [70. 65. 74.]
 [93. 95. 91.]
 [79. 80. 73.]
 [70. 73. 78.]
 [93. 89. 96.]
 [78. 75. 68.]
 [81. 90. 93.]
 [88. 92. 86.]
 [78. 83. 77.]] 
y_batch: 
 [[141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]]
x_batch: 
 [[ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]
 [ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 
y_batch: 
 [[177.]
 [175.]
 [175.]
 [149.]
 [192.]
 [152.]
 [185.]
 [180.]
 [196.]
 [142.]

In [14]:
coord.request_stop()
coord.join(threads)

In [15]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[185.33531]]
Other scores will be [[178.36246]
 [177.03688]]
