# Multi variable linear regression(2)
multi-variable linear regression using matrix

In [1]:
import tensorflow as tf
tf.set_random_seed(777) # for reproducibility

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [3]:
# placeholders for a tensor that will be always fed.
# None의 경우 임의로 주어지는 인풋 크기만큼 할당될 것 
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [4]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [5]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [6]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [7]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [8]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22655.951 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [22.293005]
 [18.633902]]
10 Cost:  6.04177 
Prediction:
 [[155.17453]
 [181.64262]
 [181.76219]
 [193.98837]
 [140.69337]]
20 Cost:  5.813164 
Prediction:
 [[155.56952]
 [182.1321 ]
 [182.23676]
 [194.50674]
 [141.06909]]
30 Cost:  5.7920384 
Prediction:
 [[155.56291]
 [182.13884]
 [182.23572]
 [194.50717]
 [141.07661]]
40 Cost:  5.771016 
Prediction:
 [[155.55511]
 [182.14413]
 [182.23325]
 [194.50603]
 [141.08298]]
50 Cost:  5.7501135 
Prediction:
 [[155.54735]
 [182.1494 ]
 [182.23079]
 [194.50493]
 [141.08934]]
60 Cost:  5.729344 
Prediction:
 [[155.53957]
 [182.15462]
 [182.22832]
 [194.50375]
 [141.09566]]
70 Cost:  5.708628 
Prediction:
 [[155.53186]
 [182.15988]
 [182.22586]
 [194.50269]
 [141.10199]]
80 Cost:  5.688075 
Prediction:
 [[155.52415]
 [182.16512]
 [182.22343]
 [194.50156]
 [141.10829]]
90 Cost:  5.6675906 
Prediction:
 [[155.51643]
 [182.17029]
 [182.22095]
 [194.50043]
 [141.11453]]
100 Cost

880 Cost:  4.3428664 
Prediction:
 [[154.96776]
 [182.54124]
 [182.04619]
 [194.42554]
 [141.5579 ]]
890 Cost:  4.3293123 
Prediction:
 [[154.96152]
 [182.54547]
 [182.0442 ]
 [194.42474]
 [141.5629 ]]
900 Cost:  4.315819 
Prediction:
 [[154.9553 ]
 [182.5497 ]
 [182.04222]
 [194.42397]
 [141.56789]]
910 Cost:  4.302401 
Prediction:
 [[154.94908]
 [182.55386]
 [182.0402 ]
 [194.42316]
 [141.57285]]
920 Cost:  4.2890196 
Prediction:
 [[154.94289]
 [182.55807]
 [182.03824]
 [194.4224 ]
 [141.57779]]
930 Cost:  4.27576 
Prediction:
 [[154.93669]
 [182.56223]
 [182.03625]
 [194.42157]
 [141.58272]]
940 Cost:  4.2625113 
Prediction:
 [[154.93051]
 [182.56639]
 [182.03427]
 [194.42079]
 [141.58763]]
950 Cost:  4.2493653 
Prediction:
 [[154.92438]
 [182.57056]
 [182.03233]
 [194.42004]
 [141.59256]]
960 Cost:  4.2363176 
Prediction:
 [[154.91824]
 [182.57468]
 [182.03035]
 [194.41922]
 [141.59743]]
970 Cost:  4.223239 
Prediction:
 [[154.91212]
 [182.57884]
 [182.0284 ]
 [194.41849]
 [141.602

1780 Cost:  3.3593411 
Prediction:
 [[154.46538]
 [182.87984]
 [181.88483]
 [194.36635]
 [141.95377]]
1790 Cost:  3.3506825 
Prediction:
 [[154.4604 ]
 [182.88316]
 [181.8832 ]
 [194.3658 ]
 [141.95758]]
1800 Cost:  3.3421464 
Prediction:
 [[154.4555 ]
 [182.8865 ]
 [181.88165]
 [194.3653 ]
 [141.96143]]
1810 Cost:  3.3335762 
Prediction:
 [[154.45056]
 [182.8898 ]
 [181.88002]
 [194.36476]
 [141.96524]]
1820 Cost:  3.3250313 
Prediction:
 [[154.44563]
 [182.89313]
 [181.87843]
 [194.36426]
 [141.96904]]
1830 Cost:  3.316608 
Prediction:
 [[154.44073]
 [182.8964 ]
 [181.87685]
 [194.36372]
 [141.97284]]
1840 Cost:  3.3081737 
Prediction:
 [[154.43585]
 [182.8997 ]
 [181.87527]
 [194.36322]
 [141.9766 ]]
1850 Cost:  3.299787 
Prediction:
 [[154.43097]
 [182.90297]
 [181.87369]
 [194.36272]
 [141.9804 ]]
1860 Cost:  3.2914512 
Prediction:
 [[154.42612]
 [182.90625]
 [181.87213]
 [194.36223]
 [141.98415]]
1870 Cost:  3.283134 
Prediction:
 [[154.42126]
 [182.90953]
 [181.87056]
 [194.3617